2017-05-11 09:25:27,126 - __main__ - ERROR - Trajectory: failed to update on POST information
Traceback (most recent call last):
  File "app.py", line 272, in post
    self.data_raw = json.dumps(request.get_json(force=True)[0]).encode('utf8')
IndexError: list index out of range
